# Site settings
title: funccode
description: "My exploration of programming and Swift"
url: "https://xmasrights.github.io/funccode"
author:
  name: "Christopher Fonseka"
  email: "chris.fonseka@googlemail.com"
  url: "https://xmasrights.github.io"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
